// <auto-generated />
namespace RDN.DBUpdate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class AddLinks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLinks));
        
        string IMigrationMetadata.Id
        {
            get { return "201509121333565_AddLinks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
