#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RDNation.Droid.Resource", IsApplication=true)]

namespace RDNation.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LegacyBar.Library.Resource.Attribute.background = global::RDNation.Droid.Resource.Attribute.background;
			global::LegacyBar.Library.Resource.Attribute.background_item = global::RDNation.Droid.Resource.Attribute.background_item;
			global::LegacyBar.Library.Resource.Attribute.is_bottom = global::RDNation.Droid.Resource.Attribute.is_bottom;
			global::LegacyBar.Library.Resource.Attribute.light_icons = global::RDNation.Droid.Resource.Attribute.light_icons;
			global::LegacyBar.Library.Resource.Attribute.separator = global::RDNation.Droid.Resource.Attribute.separator;
			global::LegacyBar.Library.Resource.Attribute.theme = global::RDNation.Droid.Resource.Attribute.theme;
			global::LegacyBar.Library.Resource.Attribute.title = global::RDNation.Droid.Resource.Attribute.title;
			global::LegacyBar.Library.Resource.Attribute.title_color = global::RDNation.Droid.Resource.Attribute.title_color;
			global::LegacyBar.Library.Resource.Color.Red = global::RDNation.Droid.Resource.Color.Red;
			global::LegacyBar.Library.Resource.Color.actionbar_accentcolor_black = global::RDNation.Droid.Resource.Color.actionbar_accentcolor_black;
			global::LegacyBar.Library.Resource.Color.actionbar_accentcolor_blue = global::RDNation.Droid.Resource.Color.actionbar_accentcolor_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_accentcolor_darkgray = global::RDNation.Droid.Resource.Color.actionbar_accentcolor_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_accentcolor_lightgray = global::RDNation.Droid.Resource.Color.actionbar_accentcolor_lightgray;
			global::LegacyBar.Library.Resource.Color.actionbar_background_end = global::RDNation.Droid.Resource.Color.actionbar_background_end;
			global::LegacyBar.Library.Resource.Color.actionbar_background_end_alt = global::RDNation.Droid.Resource.Color.actionbar_background_end_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_end = global::RDNation.Droid.Resource.Color.actionbar_background_item_pressed_end;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_end_alt = global::RDNation.Droid.Resource.Color.actionbar_background_item_pressed_end_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_start = global::RDNation.Droid.Resource.Color.actionbar_background_item_pressed_start;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_start_alt = global::RDNation.Droid.Resource.Color.actionbar_background_item_pressed_start_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_background_start = global::RDNation.Droid.Resource.Color.actionbar_background_start;
			global::LegacyBar.Library.Resource.Color.actionbar_background_start_alt = global::RDNation.Droid.Resource.Color.actionbar_background_start_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_maincolor_black = global::RDNation.Droid.Resource.Color.actionbar_maincolor_black;
			global::LegacyBar.Library.Resource.Color.actionbar_maincolor_blue = global::RDNation.Droid.Resource.Color.actionbar_maincolor_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_maincolor_darkgray = global::RDNation.Droid.Resource.Color.actionbar_maincolor_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_maincolor_lightgray = global::RDNation.Droid.Resource.Color.actionbar_maincolor_lightgray;
			global::LegacyBar.Library.Resource.Color.actionbar_pressedcolor_black = global::RDNation.Droid.Resource.Color.actionbar_pressedcolor_black;
			global::LegacyBar.Library.Resource.Color.actionbar_pressedcolor_blue = global::RDNation.Droid.Resource.Color.actionbar_pressedcolor_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_pressedcolor_darkgray = global::RDNation.Droid.Resource.Color.actionbar_pressedcolor_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_pressedcolor_lightgray = global::RDNation.Droid.Resource.Color.actionbar_pressedcolor_lightgray;
			global::LegacyBar.Library.Resource.Color.actionbar_separator = global::RDNation.Droid.Resource.Color.actionbar_separator;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_alt = global::RDNation.Droid.Resource.Color.actionbar_separator_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_black = global::RDNation.Droid.Resource.Color.actionbar_separator_black;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_blue = global::RDNation.Droid.Resource.Color.actionbar_separator_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_darkgray = global::RDNation.Droid.Resource.Color.actionbar_separator_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_lightgray = global::RDNation.Droid.Resource.Color.actionbar_separator_lightgray;
			global::LegacyBar.Library.Resource.Color.actionbar_title = global::RDNation.Droid.Resource.Color.actionbar_title;
			global::LegacyBar.Library.Resource.Color.actionbar_title_alt = global::RDNation.Droid.Resource.Color.actionbar_title_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_title_black = global::RDNation.Droid.Resource.Color.actionbar_title_black;
			global::LegacyBar.Library.Resource.Color.actionbar_title_blue = global::RDNation.Droid.Resource.Color.actionbar_title_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_title_darkgray = global::RDNation.Droid.Resource.Color.actionbar_title_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_title_lightgray = global::RDNation.Droid.Resource.Color.actionbar_title_lightgray;
			global::LegacyBar.Library.Resource.Color.black = global::RDNation.Droid.Resource.Color.black;
			global::LegacyBar.Library.Resource.Color.blue = global::RDNation.Droid.Resource.Color.blue;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_end = global::RDNation.Droid.Resource.Color.bottomactionbar_background_end;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_item_pressed_end = global::RDNation.Droid.Resource.Color.bottomactionbar_background_item_pressed_end;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_item_pressed_start = global::RDNation.Droid.Resource.Color.bottomactionbar_background_item_pressed_start;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_start = global::RDNation.Droid.Resource.Color.bottomactionbar_background_start;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_black = global::RDNation.Droid.Resource.Color.bottomactionbar_maincolor_black;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_blue = global::RDNation.Droid.Resource.Color.bottomactionbar_maincolor_blue;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_darkgray = global::RDNation.Droid.Resource.Color.bottomactionbar_maincolor_darkgray;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_lightgray = global::RDNation.Droid.Resource.Color.bottomactionbar_maincolor_lightgray;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_black = global::RDNation.Droid.Resource.Color.bottomactionbar_pressedcolor_black;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_blue = global::RDNation.Droid.Resource.Color.bottomactionbar_pressedcolor_blue;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_darkgray = global::RDNation.Droid.Resource.Color.bottomactionbar_pressedcolor_darkgray;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_lightgray = global::RDNation.Droid.Resource.Color.bottomactionbar_pressedcolor_lightgray;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_separator = global::RDNation.Droid.Resource.Color.bottomactionbar_separator;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_title = global::RDNation.Droid.Resource.Color.bottomactionbar_title;
			global::LegacyBar.Library.Resource.Color.green = global::RDNation.Droid.Resource.Color.green;
			global::LegacyBar.Library.Resource.Color.grey = global::RDNation.Droid.Resource.Color.grey;
			global::LegacyBar.Library.Resource.Color.pager_black = global::RDNation.Droid.Resource.Color.pager_black;
			global::LegacyBar.Library.Resource.Color.pager_blue = global::RDNation.Droid.Resource.Color.pager_blue;
			global::LegacyBar.Library.Resource.Color.pager_darkgray = global::RDNation.Droid.Resource.Color.pager_darkgray;
			global::LegacyBar.Library.Resource.Color.pager_lightgray = global::RDNation.Droid.Resource.Color.pager_lightgray;
			global::LegacyBar.Library.Resource.Color.red = global::RDNation.Droid.Resource.Color.red;
			global::LegacyBar.Library.Resource.Color.white = global::RDNation.Droid.Resource.Color.white;
			global::LegacyBar.Library.Resource.Color.yellow = global::RDNation.Droid.Resource.Color.yellow;
			global::LegacyBar.Library.Resource.Dimension.actionbar_accentheight = global::RDNation.Droid.Resource.Dimension.actionbar_accentheight;
			global::LegacyBar.Library.Resource.Dimension.actionbar_height = global::RDNation.Droid.Resource.Dimension.actionbar_height;
			global::LegacyBar.Library.Resource.Dimension.actionbar_home_item_width = global::RDNation.Droid.Resource.Dimension.actionbar_home_item_width;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_height = global::RDNation.Droid.Resource.Dimension.actionbar_item_height;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_height_over = global::RDNation.Droid.Resource.Dimension.actionbar_item_height_over;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_height_overflow = global::RDNation.Droid.Resource.Dimension.actionbar_item_height_overflow;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_width = global::RDNation.Droid.Resource.Dimension.actionbar_item_width;
			global::LegacyBar.Library.Resource.Drawable.actionbar_back_indicator = global::RDNation.Droid.Resource.Drawable.actionbar_back_indicator;
			global::LegacyBar.Library.Resource.Drawable.actionbar_back_indicator_dark = global::RDNation.Droid.Resource.Drawable.actionbar_back_indicator_dark;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background = global::RDNation.Droid.Resource.Drawable.actionbar_background;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_alt = global::RDNation.Droid.Resource.Drawable.actionbar_background_alt;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_black = global::RDNation.Droid.Resource.Drawable.actionbar_background_black;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_blue = global::RDNation.Droid.Resource.Drawable.actionbar_background_blue;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_darkgray = global::RDNation.Droid.Resource.Drawable.actionbar_background_darkgray;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_lightgray = global::RDNation.Droid.Resource.Drawable.actionbar_background_lightgray;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn = global::RDNation.Droid.Resource.Drawable.actionbar_btn;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_alt = global::RDNation.Droid.Resource.Drawable.actionbar_btn_alt;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_black = global::RDNation.Droid.Resource.Drawable.actionbar_btn_black;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_blue = global::RDNation.Droid.Resource.Drawable.actionbar_btn_blue;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_darkgray = global::RDNation.Droid.Resource.Drawable.actionbar_btn_darkgray;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_lightgray = global::RDNation.Droid.Resource.Drawable.actionbar_btn_lightgray;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_normal = global::RDNation.Droid.Resource.Drawable.actionbar_btn_normal;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_normal_alt = global::RDNation.Droid.Resource.Drawable.actionbar_btn_normal_alt;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_pressed = global::RDNation.Droid.Resource.Drawable.actionbar_btn_pressed;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_pressed_alt = global::RDNation.Droid.Resource.Drawable.actionbar_btn_pressed_alt;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background = global::RDNation.Droid.Resource.Drawable.bottomactionbar_background;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background_black = global::RDNation.Droid.Resource.Drawable.bottomactionbar_background_black;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background_blue = global::RDNation.Droid.Resource.Drawable.bottomactionbar_background_blue;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background_darkgray = global::RDNation.Droid.Resource.Drawable.bottomactionbar_background_darkgray;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background_lightgray = global::RDNation.Droid.Resource.Drawable.bottomactionbar_background_lightgray;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn = global::RDNation.Droid.Resource.Drawable.bottomactionbar_btn;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_black = global::RDNation.Droid.Resource.Drawable.bottomactionbar_btn_black;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_blue = global::RDNation.Droid.Resource.Drawable.bottomactionbar_btn_blue;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_darkgray = global::RDNation.Droid.Resource.Drawable.bottomactionbar_btn_darkgray;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_lightgray = global::RDNation.Droid.Resource.Drawable.bottomactionbar_btn_lightgray;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_normal = global::RDNation.Droid.Resource.Drawable.bottomactionbar_btn_normal;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_pressed = global::RDNation.Droid.Resource.Drawable.bottomactionbar_btn_pressed;
			global::LegacyBar.Library.Resource.Drawable.dropdown_btn_holo_dark = global::RDNation.Droid.Resource.Drawable.dropdown_btn_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_btn_holo_light = global::RDNation.Droid.Resource.Drawable.dropdown_btn_holo_light;
			global::LegacyBar.Library.Resource.Drawable.dropdown_disabled_holo_dark = global::RDNation.Droid.Resource.Drawable.dropdown_disabled_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_disabled_holo_light = global::RDNation.Droid.Resource.Drawable.dropdown_disabled_holo_light;
			global::LegacyBar.Library.Resource.Drawable.dropdown_focused_holo_dark = global::RDNation.Droid.Resource.Drawable.dropdown_focused_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_focused_holo_light = global::RDNation.Droid.Resource.Drawable.dropdown_focused_holo_light;
			global::LegacyBar.Library.Resource.Drawable.dropdown_normal_holo_dark = global::RDNation.Droid.Resource.Drawable.dropdown_normal_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_normal_holo_light = global::RDNation.Droid.Resource.Drawable.dropdown_normal_holo_light;
			global::LegacyBar.Library.Resource.Drawable.dropdown_pressed_holo_dark = global::RDNation.Droid.Resource.Drawable.dropdown_pressed_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_pressed_holo_light = global::RDNation.Droid.Resource.Drawable.dropdown_pressed_holo_light;
			global::LegacyBar.Library.Resource.Drawable.ic_action_overflow = global::RDNation.Droid.Resource.Drawable.ic_action_overflow;
			global::LegacyBar.Library.Resource.Drawable.ic_action_overflow_dark = global::RDNation.Droid.Resource.Drawable.ic_action_overflow_dark;
			global::LegacyBar.Library.Resource.Id.actionbar_actions = global::RDNation.Droid.Resource.Id.actionbar_actions;
			global::LegacyBar.Library.Resource.Id.actionbar_home = global::RDNation.Droid.Resource.Id.actionbar_home;
			global::LegacyBar.Library.Resource.Id.actionbar_home_bg = global::RDNation.Droid.Resource.Id.actionbar_home_bg;
			global::LegacyBar.Library.Resource.Id.actionbar_home_btn = global::RDNation.Droid.Resource.Id.actionbar_home_btn;
			global::LegacyBar.Library.Resource.Id.actionbar_home_is_back = global::RDNation.Droid.Resource.Id.actionbar_home_is_back;
			global::LegacyBar.Library.Resource.Id.actionbar_home_logo = global::RDNation.Droid.Resource.Id.actionbar_home_logo;
			global::LegacyBar.Library.Resource.Id.actionbar_item = global::RDNation.Droid.Resource.Id.actionbar_item;
			global::LegacyBar.Library.Resource.Id.actionbar_progress = global::RDNation.Droid.Resource.Id.actionbar_progress;
			global::LegacyBar.Library.Resource.Id.actionbar_spinner = global::RDNation.Droid.Resource.Id.actionbar_spinner;
			global::LegacyBar.Library.Resource.Id.actionbar_title = global::RDNation.Droid.Resource.Id.actionbar_title;
			global::LegacyBar.Library.Resource.Id.actionbar_title_layout = global::RDNation.Droid.Resource.Id.actionbar_title_layout;
			global::LegacyBar.Library.Resource.Id.custom = global::RDNation.Droid.Resource.Id.custom;
			global::LegacyBar.Library.Resource.Id.holo_black = global::RDNation.Droid.Resource.Id.holo_black;
			global::LegacyBar.Library.Resource.Id.holo_blue = global::RDNation.Droid.Resource.Id.holo_blue;
			global::LegacyBar.Library.Resource.Id.holo_gray = global::RDNation.Droid.Resource.Id.holo_gray;
			global::LegacyBar.Library.Resource.Id.holo_light = global::RDNation.Droid.Resource.Id.holo_light;
			global::LegacyBar.Library.Resource.Id.overflow_spinner = global::RDNation.Droid.Resource.Id.overflow_spinner;
			global::LegacyBar.Library.Resource.Id.screen = global::RDNation.Droid.Resource.Id.screen;
			global::LegacyBar.Library.Resource.Layout.actionbar = global::RDNation.Droid.Resource.Layout.actionbar;
			global::LegacyBar.Library.Resource.Layout.actionbar_item = global::RDNation.Droid.Resource.Layout.actionbar_item;
			global::LegacyBar.Library.Resource.Layout.blankspinner = global::RDNation.Droid.Resource.Layout.blankspinner;
			global::LegacyBar.Library.Resource.Layout.overflowactionbar_item = global::RDNation.Droid.Resource.Layout.overflowactionbar_item;
			global::LegacyBar.Library.Resource.Layout.spinneritem = global::RDNation.Droid.Resource.Layout.spinneritem;
			global::LegacyBar.Library.Resource.String.actionbar_activity_not_found = global::RDNation.Droid.Resource.String.actionbar_activity_not_found;
			global::LegacyBar.Library.Resource.Style.actionbar = global::RDNation.Droid.Resource.Style.actionbar;
			global::LegacyBar.Library.Resource.Style.actionbarhomeitem = global::RDNation.Droid.Resource.Style.actionbarhomeitem;
			global::LegacyBar.Library.Resource.Style.actionbarhomelogo = global::RDNation.Droid.Resource.Style.actionbarhomelogo;
			global::LegacyBar.Library.Resource.Style.actionbaritem = global::RDNation.Droid.Resource.Style.actionbaritem;
			global::LegacyBar.Library.Resource.Style.actionbarprogressbar = global::RDNation.Droid.Resource.Style.actionbarprogressbar;
			global::LegacyBar.Library.Resource.Style.clearbutton = global::RDNation.Droid.Resource.Style.clearbutton;
			global::LegacyBar.Library.Resource.Styleable.actionbar = global::RDNation.Droid.Resource.Styleable.actionbar;
			global::LegacyBar.Library.Resource.Styleable.actionbar_background = global::RDNation.Droid.Resource.Styleable.actionbar_background;
			global::LegacyBar.Library.Resource.Styleable.actionbar_background_item = global::RDNation.Droid.Resource.Styleable.actionbar_background_item;
			global::LegacyBar.Library.Resource.Styleable.actionbar_is_bottom = global::RDNation.Droid.Resource.Styleable.actionbar_is_bottom;
			global::LegacyBar.Library.Resource.Styleable.actionbar_light_icons = global::RDNation.Droid.Resource.Styleable.actionbar_light_icons;
			global::LegacyBar.Library.Resource.Styleable.actionbar_separator = global::RDNation.Droid.Resource.Styleable.actionbar_separator;
			global::LegacyBar.Library.Resource.Styleable.actionbar_theme = global::RDNation.Droid.Resource.Styleable.actionbar_theme;
			global::LegacyBar.Library.Resource.Styleable.actionbar_title = global::RDNation.Droid.Resource.Styleable.actionbar_title;
			global::LegacyBar.Library.Resource.Styleable.actionbar_title_color = global::RDNation.Droid.Resource.Styleable.actionbar_title_color;
			global::SlidingMenuSharp.Resource.Attribute.behindOffset = global::RDNation.Droid.Resource.Attribute.behindOffset;
			global::SlidingMenuSharp.Resource.Attribute.behindScrollScale = global::RDNation.Droid.Resource.Attribute.behindScrollScale;
			global::SlidingMenuSharp.Resource.Attribute.behindWidth = global::RDNation.Droid.Resource.Attribute.behindWidth;
			global::SlidingMenuSharp.Resource.Attribute.fadeDegree = global::RDNation.Droid.Resource.Attribute.fadeDegree;
			global::SlidingMenuSharp.Resource.Attribute.fadeEnabled = global::RDNation.Droid.Resource.Attribute.fadeEnabled;
			global::SlidingMenuSharp.Resource.Attribute.mode = global::RDNation.Droid.Resource.Attribute.mode;
			global::SlidingMenuSharp.Resource.Attribute.selectorDrawable = global::RDNation.Droid.Resource.Attribute.selectorDrawable;
			global::SlidingMenuSharp.Resource.Attribute.selectorEnabled = global::RDNation.Droid.Resource.Attribute.selectorEnabled;
			global::SlidingMenuSharp.Resource.Attribute.shadowDrawable = global::RDNation.Droid.Resource.Attribute.shadowDrawable;
			global::SlidingMenuSharp.Resource.Attribute.shadowWidth = global::RDNation.Droid.Resource.Attribute.shadowWidth;
			global::SlidingMenuSharp.Resource.Attribute.touchModeAbove = global::RDNation.Droid.Resource.Attribute.touchModeAbove;
			global::SlidingMenuSharp.Resource.Attribute.touchModeBehind = global::RDNation.Droid.Resource.Attribute.touchModeBehind;
			global::SlidingMenuSharp.Resource.Attribute.viewAbove = global::RDNation.Droid.Resource.Attribute.viewAbove;
			global::SlidingMenuSharp.Resource.Attribute.viewBehind = global::RDNation.Droid.Resource.Attribute.viewBehind;
			global::SlidingMenuSharp.Resource.Id.fullscreen = global::RDNation.Droid.Resource.Id.fullscreen;
			global::SlidingMenuSharp.Resource.Id.left = global::RDNation.Droid.Resource.Id.left;
			global::SlidingMenuSharp.Resource.Id.margin = global::RDNation.Droid.Resource.Id.margin;
			global::SlidingMenuSharp.Resource.Id.right = global::RDNation.Droid.Resource.Id.right;
			global::SlidingMenuSharp.Resource.Id.selected_view = global::RDNation.Droid.Resource.Id.selected_view;
			global::SlidingMenuSharp.Resource.Id.slidingmenumain = global::RDNation.Droid.Resource.Id.slidingmenumain;
			global::SlidingMenuSharp.Resource.Layout.slidingmenumain = global::RDNation.Droid.Resource.Layout.slidingmenumain;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu = global::RDNation.Droid.Resource.Styleable.SlidingMenu;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindOffset = global::RDNation.Droid.Resource.Styleable.SlidingMenu_behindOffset;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindScrollScale = global::RDNation.Droid.Resource.Styleable.SlidingMenu_behindScrollScale;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindWidth = global::RDNation.Droid.Resource.Styleable.SlidingMenu_behindWidth;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_fadeDegree = global::RDNation.Droid.Resource.Styleable.SlidingMenu_fadeDegree;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_fadeEnabled = global::RDNation.Droid.Resource.Styleable.SlidingMenu_fadeEnabled;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_mode = global::RDNation.Droid.Resource.Styleable.SlidingMenu_mode;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_selectorDrawable = global::RDNation.Droid.Resource.Styleable.SlidingMenu_selectorDrawable;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_selectorEnabled = global::RDNation.Droid.Resource.Styleable.SlidingMenu_selectorEnabled;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_shadowDrawable = global::RDNation.Droid.Resource.Styleable.SlidingMenu_shadowDrawable;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_shadowWidth = global::RDNation.Droid.Resource.Styleable.SlidingMenu_shadowWidth;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_touchModeAbove = global::RDNation.Droid.Resource.Styleable.SlidingMenu_touchModeAbove;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_touchModeBehind = global::RDNation.Droid.Resource.Styleable.SlidingMenu_touchModeBehind;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_viewAbove = global::RDNation.Droid.Resource.Styleable.SlidingMenu_viewAbove;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_viewBehind = global::RDNation.Droid.Resource.Styleable.SlidingMenu_viewBehind;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0a0000
			public const int gender_array = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int position_array = 2131361793;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010011
			public const int background = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int background_item = 2130771986;
			
			// aapt resource value: 0x7f010003
			public const int behindOffset = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int behindScrollScale = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int behindWidth = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int fadeDegree = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int fadeEnabled = 2130771978;
			
			// aapt resource value: 0x7f010014
			public const int is_bottom = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int light_icons = 2130771989;
			
			// aapt resource value: 0x7f010000
			public const int mode = 2130771968;
			
			// aapt resource value: 0x7f01000d
			public const int selectorDrawable = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int selectorEnabled = 2130771980;
			
			// aapt resource value: 0x7f010010
			public const int separator = 2130771984;
			
			// aapt resource value: 0x7f010008
			public const int shadowDrawable = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int shadowWidth = 2130771977;
			
			// aapt resource value: 0x7f010013
			public const int theme = 2130771987;
			
			// aapt resource value: 0x7f01000e
			public const int title = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int title_color = 2130771983;
			
			// aapt resource value: 0x7f010006
			public const int touchModeAbove = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int touchModeBehind = 2130771975;
			
			// aapt resource value: 0x7f010001
			public const int viewAbove = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int viewBehind = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050039
			public const int Red = 2131034169;
			
			// aapt resource value: 0x7f050023
			public const int actionbar_accentcolor_black = 2131034147;
			
			// aapt resource value: 0x7f05002b
			public const int actionbar_accentcolor_blue = 2131034155;
			
			// aapt resource value: 0x7f05001b
			public const int actionbar_accentcolor_darkgray = 2131034139;
			
			// aapt resource value: 0x7f050013
			public const int actionbar_accentcolor_lightgray = 2131034131;
			
			// aapt resource value: 0x7f050003
			public const int actionbar_background_end = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int actionbar_background_end_alt = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int actionbar_background_item_pressed_end = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int actionbar_background_item_pressed_end_alt = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int actionbar_background_item_pressed_start = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int actionbar_background_item_pressed_start_alt = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int actionbar_background_start = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int actionbar_background_start_alt = 2131034120;
			
			// aapt resource value: 0x7f050022
			public const int actionbar_maincolor_black = 2131034146;
			
			// aapt resource value: 0x7f05002a
			public const int actionbar_maincolor_blue = 2131034154;
			
			// aapt resource value: 0x7f05001a
			public const int actionbar_maincolor_darkgray = 2131034138;
			
			// aapt resource value: 0x7f050012
			public const int actionbar_maincolor_lightgray = 2131034130;
			
			// aapt resource value: 0x7f050024
			public const int actionbar_pressedcolor_black = 2131034148;
			
			// aapt resource value: 0x7f05002c
			public const int actionbar_pressedcolor_blue = 2131034156;
			
			// aapt resource value: 0x7f05001c
			public const int actionbar_pressedcolor_darkgray = 2131034140;
			
			// aapt resource value: 0x7f050014
			public const int actionbar_pressedcolor_lightgray = 2131034132;
			
			// aapt resource value: 0x7f050000
			public const int actionbar_separator = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int actionbar_separator_alt = 2131034118;
			
			// aapt resource value: 0x7f050026
			public const int actionbar_separator_black = 2131034150;
			
			// aapt resource value: 0x7f05002e
			public const int actionbar_separator_blue = 2131034158;
			
			// aapt resource value: 0x7f05001e
			public const int actionbar_separator_darkgray = 2131034142;
			
			// aapt resource value: 0x7f050016
			public const int actionbar_separator_lightgray = 2131034134;
			
			// aapt resource value: 0x7f050001
			public const int actionbar_title = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int actionbar_title_alt = 2131034119;
			
			// aapt resource value: 0x7f050025
			public const int actionbar_title_black = 2131034149;
			
			// aapt resource value: 0x7f05002d
			public const int actionbar_title_blue = 2131034157;
			
			// aapt resource value: 0x7f05001d
			public const int actionbar_title_darkgray = 2131034141;
			
			// aapt resource value: 0x7f050015
			public const int actionbar_title_lightgray = 2131034133;
			
			// aapt resource value: 0x7f050033
			public const int black = 2131034163;
			
			// aapt resource value: 0x7f050036
			public const int blue = 2131034166;
			
			// aapt resource value: 0x7f05000f
			public const int bottomactionbar_background_end = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int bottomactionbar_background_item_pressed_end = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int bottomactionbar_background_item_pressed_start = 2131034129;
			
			// aapt resource value: 0x7f05000e
			public const int bottomactionbar_background_start = 2131034126;
			
			// aapt resource value: 0x7f050027
			public const int bottomactionbar_maincolor_black = 2131034151;
			
			// aapt resource value: 0x7f05002f
			public const int bottomactionbar_maincolor_blue = 2131034159;
			
			// aapt resource value: 0x7f05001f
			public const int bottomactionbar_maincolor_darkgray = 2131034143;
			
			// aapt resource value: 0x7f050017
			public const int bottomactionbar_maincolor_lightgray = 2131034135;
			
			// aapt resource value: 0x7f050028
			public const int bottomactionbar_pressedcolor_black = 2131034152;
			
			// aapt resource value: 0x7f050030
			public const int bottomactionbar_pressedcolor_blue = 2131034160;
			
			// aapt resource value: 0x7f050020
			public const int bottomactionbar_pressedcolor_darkgray = 2131034144;
			
			// aapt resource value: 0x7f050018
			public const int bottomactionbar_pressedcolor_lightgray = 2131034136;
			
			// aapt resource value: 0x7f05000c
			public const int bottomactionbar_separator = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int bottomactionbar_title = 2131034125;
			
			// aapt resource value: 0x7f05003d
			public const int gray = 2131034173;
			
			// aapt resource value: 0x7f050034
			public const int green = 2131034164;
			
			// aapt resource value: 0x7f050037
			public const int grey = 2131034167;
			
			// aapt resource value: 0x7f050029
			public const int pager_black = 2131034153;
			
			// aapt resource value: 0x7f050031
			public const int pager_blue = 2131034161;
			
			// aapt resource value: 0x7f050021
			public const int pager_darkgray = 2131034145;
			
			// aapt resource value: 0x7f050019
			public const int pager_lightgray = 2131034137;
			
			// aapt resource value: 0x7f05003a
			public const int purple = 2131034170;
			
			// aapt resource value: 0x7f05003c
			public const int purpledark = 2131034172;
			
			// aapt resource value: 0x7f05003b
			public const int purplelight = 2131034171;
			
			// aapt resource value: 0x7f050035
			public const int red = 2131034165;
			
			// aapt resource value: 0x7f050032
			public const int white = 2131034162;
			
			// aapt resource value: 0x7f050038
			public const int yellow = 2131034168;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int actionbar_accentheight = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int actionbar_height = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int actionbar_home_item_width = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int actionbar_item_height = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int actionbar_item_height_over = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int actionbar_item_height_overflow = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int actionbar_item_width = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int list_padding = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int shadow_width = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int slidingmenu_offset = 2131099655;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int a_z = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int action_about = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int action_settings = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int actionbar_back_indicator = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int actionbar_back_indicator_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int actionbar_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int actionbar_background_alt = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int actionbar_background_black = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int actionbar_background_blue = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int actionbar_background_darkgray = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int actionbar_background_lightgray = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int actionbar_btn = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int actionbar_btn_alt = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int actionbar_btn_black = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int actionbar_btn_blue = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int actionbar_btn_darkgray = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int actionbar_btn_lightgray = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int actionbar_btn_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int actionbar_btn_normal_alt = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int actionbar_btn_pressed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int actionbar_btn_pressed_alt = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int background = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int backgroundNavigation = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int bottomactionbar_background = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int bottomactionbar_background_black = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int bottomactionbar_background_blue = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int bottomactionbar_background_darkgray = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int bottomactionbar_background_lightgray = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int bottomactionbar_btn = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int bottomactionbar_btn_black = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int bottomactionbar_btn_blue = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int bottomactionbar_btn_darkgray = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int bottomactionbar_btn_lightgray = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int bottomactionbar_btn_normal = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int bottomactionbar_btn_pressed = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int buttonMainStyle = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int buy_now_button = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int calendar = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int contentBoxContent = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int contentBoxHeadBackground = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int dropdown_btn_holo_dark = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int dropdown_btn_holo_light = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int dropdown_disabled_holo_dark = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int dropdown_disabled_holo_light = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int dropdown_focused_holo_dark = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int dropdown_focused_holo_light = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int dropdown_normal_holo_dark = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int dropdown_normal_holo_light = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int dropdown_pressed_holo_dark = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int dropdown_pressed_holo_light = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int games = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int home = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_action_data_ticket_icon = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_action_down = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_action_down_dark = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic_action_left = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ic_action_left_dark = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ic_action_overflow = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ic_action_overflow_dark = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ic_action_refresh = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ic_action_refresh_dark = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic_action_right = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic_action_right_dark = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic_action_search = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ic_action_search_dark = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ic_action_share = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ic_action_share_dark = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ic_action_sort = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ic_action_sort_dark = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int ic_action_up = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int ic_action_up_dark = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int ic_launcher = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int ic_menu_down = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int ic_menu_left = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int ic_menu_refresh = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int ic_menu_right = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int ic_menu_search = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int ic_menu_up = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int icon = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int location_place = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int more = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int profile_cell_shape = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int profile_cell_shape_header = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int profile_info_cell = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int profileTeamNameButton = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int publicGameRowBackground = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int rollerball = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int rowSelected = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int shadow = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int shop = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int skater = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int social_add_person = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int social_person = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int splash = 2130837597;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04007d
			public const int ProfileNameNumber = 2130968701;
			
			// aapt resource value: 0x7f040071
			public const int ScrollView01 = 2130968689;
			
			// aapt resource value: 0x7f040018
			public const int actionbar = 2130968600;
			
			// aapt resource value: 0x7f040010
			public const int actionbar_actions = 2130968592;
			
			// aapt resource value: 0x7f04000b
			public const int actionbar_home = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int actionbar_home_bg = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int actionbar_home_btn = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int actionbar_home_is_back = 2130968591;
			
			// aapt resource value: 0x7f04000c
			public const int actionbar_home_logo = 2130968588;
			
			// aapt resource value: 0x7f040015
			public const int actionbar_item = 2130968597;
			
			// aapt resource value: 0x7f040012
			public const int actionbar_progress = 2130968594;
			
			// aapt resource value: 0x7f040014
			public const int actionbar_spinner = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int actionbar_title = 2130968595;
			
			// aapt resource value: 0x7f040011
			public const int actionbar_title_layout = 2130968593;
			
			// aapt resource value: 0x7f040033
			public const int adView = 2130968627;
			
			// aapt resource value: 0x7f040086
			public const int ageRow = 2130968710;
			
			// aapt resource value: 0x7f040084
			public const int bio = 2130968708;
			
			// aapt resource value: 0x7f040088
			public const int bornRow = 2130968712;
			
			// aapt resource value: 0x7f040055
			public const int bottomLayout = 2130968661;
			
			// aapt resource value: 0x7f040027
			public const int calendarBtn = 2130968615;
			
			// aapt resource value: 0x7f040005
			public const int custom = 2130968581;
			
			// aapt resource value: 0x7f040072
			public const int derby = 2130968690;
			
			// aapt resource value: 0x7f040075
			public const int derbyName = 2130968693;
			
			// aapt resource value: 0x7f040077
			public const int emailAddress = 2130968695;
			
			// aapt resource value: 0x7f04002f
			public const int eventAddress = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int eventDateTime = 2130968624;
			
			// aapt resource value: 0x7f040032
			public const int eventDescription = 2130968626;
			
			// aapt resource value: 0x7f04002d
			public const int eventImage = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int eventLocation = 2130968622;
			
			// aapt resource value: 0x7f04002c
			public const int eventName = 2130968620;
			
			// aapt resource value: 0x7f040031
			public const int eventOrganizerInfo = 2130968625;
			
			// aapt resource value: 0x7f04003a
			public const int eventsList = 2130968634;
			
			// aapt resource value: 0x7f040076
			public const int firstName = 2130968694;
			
			// aapt resource value: 0x7f040003
			public const int fullscreen = 2130968579;
			
			// aapt resource value: 0x7f040026
			public const int gamesBtn = 2130968614;
			
			// aapt resource value: 0x7f040082
			public const int gamesCount = 2130968706;
			
			// aapt resource value: 0x7f04008a
			public const int heightRow = 2130968714;
			
			// aapt resource value: 0x7f040017
			public const int help = 2130968599;
			
			// aapt resource value: 0x7f040008
			public const int holo_black = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int holo_blue = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int holo_gray = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int holo_light = 2130968582;
			
			// aapt resource value: 0x7f04008f
			public const int imageView1 = 2130968719;
			
			// aapt resource value: 0x7f040053
			public const int leagueCityState = 2130968659;
			
			// aapt resource value: 0x7f040051
			public const int leagueImage = 2130968657;
			
			// aapt resource value: 0x7f04005b
			public const int leagueImageRow = 2130968667;
			
			// aapt resource value: 0x7f04005d
			public const int leagueList = 2130968669;
			
			// aapt resource value: 0x7f040058
			public const int leagueMemberTable = 2130968664;
			
			// aapt resource value: 0x7f040052
			public const int leagueName = 2130968658;
			
			// aapt resource value: 0x7f040056
			public const int leagueScheduleTable = 2130968662;
			
			// aapt resource value: 0x7f040029
			public const int leaguesBtn = 2130968617;
			
			// aapt resource value: 0x7f040000
			public const int left = 2130968576;
			
			// aapt resource value: 0x7f040024
			public const int loginBtn = 2130968612;
			
			// aapt resource value: 0x7f040020
			public const int loginControl = 2130968608;
			
			// aapt resource value: 0x7f040002
			public const int margin = 2130968578;
			
			// aapt resource value: 0x7f040093
			public const int menu_down = 2130968723;
			
			// aapt resource value: 0x7f040091
			public const int menu_left = 2130968721;
			
			// aapt resource value: 0x7f040095
			public const int menu_refresh = 2130968725;
			
			// aapt resource value: 0x7f040090
			public const int menu_right = 2130968720;
			
			// aapt resource value: 0x7f040094
			public const int menu_search = 2130968724;
			
			// aapt resource value: 0x7f040096
			public const int menu_test1 = 2130968726;
			
			// aapt resource value: 0x7f040097
			public const int menu_test2 = 2130968727;
			
			// aapt resource value: 0x7f040098
			public const int menu_test3 = 2130968728;
			
			// aapt resource value: 0x7f040092
			public const int menu_up = 2130968722;
			
			// aapt resource value: 0x7f040059
			public const int nameMemberRow = 2130968665;
			
			// aapt resource value: 0x7f040057
			public const int nameRow = 2130968663;
			
			// aapt resource value: 0x7f040016
			public const int new_game = 2130968598;
			
			// aapt resource value: 0x7f04002b
			public const int overflow_spinner = 2130968619;
			
			// aapt resource value: 0x7f040023
			public const int password = 2130968611;
			
			// aapt resource value: 0x7f040047
			public const int pastGamesList = 2130968647;
			
			// aapt resource value: 0x7f040087
			public const int profileAge = 2130968711;
			
			// aapt resource value: 0x7f040089
			public const int profileBorn = 2130968713;
			
			// aapt resource value: 0x7f04008b
			public const int profileHeight = 2130968715;
			
			// aapt resource value: 0x7f04007c
			public const int profileImage = 2130968700;
			
			// aapt resource value: 0x7f040085
			public const int profileName = 2130968709;
			
			// aapt resource value: 0x7f04007e
			public const int profileStatTable = 2130968702;
			
			// aapt resource value: 0x7f04008d
			public const int profileWeight = 2130968717;
			
			// aapt resource value: 0x7f040038
			public const int publicEventRowDetails = 2130968632;
			
			// aapt resource value: 0x7f040035
			public const int publicEventRowId = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int publicEventRowImage = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int publicEventRowName = 2130968631;
			
			// aapt resource value: 0x7f04003b
			public const int publicGameRowHeader = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int publicGameRowHeaderPeriodJam = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int publicGameRowTeamOne = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int publicGameRowTeamOneLogo = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int publicGameRowTeamOneName = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int publicGameRowTeamOneScore = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int publicGameRowTeamOneWinner = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int publicGameRowTeamTwo = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int publicGameRowTeamTwoLogo = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int publicGameRowTeamTwoName = 2130968644;
			
			// aapt resource value: 0x7f040045
			public const int publicGameRowTeamTwoScore = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int publicGameRowTeamTwoWinner = 2130968646;
			
			// aapt resource value: 0x7f04004c
			public const int publicLeagueMemberRow = 2130968652;
			
			// aapt resource value: 0x7f040034
			public const int publicLeagueRow = 2130968628;
			
			// aapt resource value: 0x7f040049
			public const int publicLeagueRowDate = 2130968649;
			
			// aapt resource value: 0x7f04004b
			public const int publicLeagueRowEventName = 2130968651;
			
			// aapt resource value: 0x7f040048
			public const int publicLeagueRowId = 2130968648;
			
			// aapt resource value: 0x7f04004d
			public const int publicLeagueRowMemberImage = 2130968653;
			
			// aapt resource value: 0x7f04004f
			public const int publicLeagueRowMemberName = 2130968655;
			
			// aapt resource value: 0x7f04004e
			public const int publicLeagueRowMemberNumber = 2130968654;
			
			// aapt resource value: 0x7f04005a
			public const int publicLeagueRowSub = 2130968666;
			
			// aapt resource value: 0x7f04004a
			public const int publicLeagueRowTime = 2130968650;
			
			// aapt resource value: 0x7f040064
			public const int publicShopRowId = 2130968676;
			
			// aapt resource value: 0x7f040065
			public const int publicShopRowImage = 2130968677;
			
			// aapt resource value: 0x7f040067
			public const int publicShopRowMadeBy = 2130968679;
			
			// aapt resource value: 0x7f040066
			public const int publicShopRowName = 2130968678;
			
			// aapt resource value: 0x7f040068
			public const int publicShopRowPrice = 2130968680;
			
			// aapt resource value: 0x7f040069
			public const int publicSkaterRow = 2130968681;
			
			// aapt resource value: 0x7f04006b
			public const int publicSkaterRowSub = 2130968683;
			
			// aapt resource value: 0x7f040074
			public const int radio_no = 2130968692;
			
			// aapt resource value: 0x7f040073
			public const int radio_yes = 2130968691;
			
			// aapt resource value: 0x7f040001
			public const int right = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int screen = 2130968586;
			
			// aapt resource value: 0x7f040039
			public const int search_events = 2130968633;
			
			// aapt resource value: 0x7f04005c
			public const int search_leagues = 2130968668;
			
			// aapt resource value: 0x7f04006f
			public const int search_skaters = 2130968687;
			
			// aapt resource value: 0x7f040004
			public const int selected_view = 2130968580;
			
			// aapt resource value: 0x7f040063
			public const int shopItemBuyNow = 2130968675;
			
			// aapt resource value: 0x7f040062
			public const int shopItemDescription = 2130968674;
			
			// aapt resource value: 0x7f04005e
			public const int shopItemImage = 2130968670;
			
			// aapt resource value: 0x7f04005f
			public const int shopItemName = 2130968671;
			
			// aapt resource value: 0x7f040061
			public const int shopItemPrice = 2130968673;
			
			// aapt resource value: 0x7f040060
			public const int shopItemSoldBy = 2130968672;
			
			// aapt resource value: 0x7f04002a
			public const int shopsBtn = 2130968618;
			
			// aapt resource value: 0x7f040025
			public const int signUpBtn = 2130968613;
			
			// aapt resource value: 0x7f04006d
			public const int skaterGender = 2130968685;
			
			// aapt resource value: 0x7f04006e
			public const int skaterImageRow = 2130968686;
			
			// aapt resource value: 0x7f040070
			public const int skaterList = 2130968688;
			
			// aapt resource value: 0x7f04006a
			public const int skaterName = 2130968682;
			
			// aapt resource value: 0x7f04006c
			public const int skaterNumber = 2130968684;
			
			// aapt resource value: 0x7f040028
			public const int skatersBtn = 2130968616;
			
			// aapt resource value: 0x7f04008e
			public const int slidingmenumain = 2130968718;
			
			// aapt resource value: 0x7f04007a
			public const int spinnerDropdown = 2130968698;
			
			// aapt resource value: 0x7f040078
			public const int spinnerGender = 2130968696;
			
			// aapt resource value: 0x7f040079
			public const int spinnerPosition = 2130968697;
			
			// aapt resource value: 0x7f040019
			public const int status = 2130968601;
			
			// aapt resource value: 0x7f04001c
			public const int statusEvents = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int statusGames = 2130968603;
			
			// aapt resource value: 0x7f04001e
			public const int statusLeagues = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int statusShops = 2130968607;
			
			// aapt resource value: 0x7f04001d
			public const int statusSkaters = 2130968605;
			
			// aapt resource value: 0x7f04001a
			public const int statusfeedback = 2130968602;
			
			// aapt resource value: 0x7f04007f
			public const int tableRow1 = 2130968703;
			
			// aapt resource value: 0x7f040081
			public const int tableRow2 = 2130968705;
			
			// aapt resource value: 0x7f040054
			public const int teamNameBtn = 2130968660;
			
			// aapt resource value: 0x7f04007b
			public const int text = 2130968699;
			
			// aapt resource value: 0x7f040080
			public const int textView1 = 2130968704;
			
			// aapt resource value: 0x7f040050
			public const int topLayout = 2130968656;
			
			// aapt resource value: 0x7f040022
			public const int userName = 2130968610;
			
			// aapt resource value: 0x7f040021
			public const int warning = 2130968609;
			
			// aapt resource value: 0x7f04008c
			public const int weightRow = 2130968716;
			
			// aapt resource value: 0x7f040083
			public const int winsLoses = 2130968707;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int num_cols = 2131296256;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int actionbar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int actionbar_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AlphaSelectorMenu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int blankspinner = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Info = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int overflowactionbar_item = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int PublicEvent = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PublicEventRow = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int PublicEvents = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PublicGameRow = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int PublicGames = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int PublicLeagueEventRow = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int PublicLeagueMemberRow = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int PublicLeagueProfile = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int PublicLeagueRow = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int PublicLeagues = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int PublicShopItem = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int PublicShopRow = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int PublicSkaterRow = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int PublicSkaters = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Signup = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int simple_spinner_dropdown_item = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int simple_spinner_item = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int SkaterProfile = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int slidingmenumain = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int spinneritem = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int splash = 2130903068;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int bottomactionbarmenus = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int mainmenu = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int othermainmenu = 2131427330;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070002
			public const int ApplicationName = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int actionbar_activity_not_found = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int gender_prompt = 2131165196;
			
			// aapt resource value: 0x7f070003
			public const int home_welcome = 2131165187;
			
			// aapt resource value: 0x7f070010
			public const int info_events = 2131165200;
			
			// aapt resource value: 0x7f07000e
			public const int info_feedback = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int info_games = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int info_leagues = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int info_shops = 2131165203;
			
			// aapt resource value: 0x7f070011
			public const int info_skaters = 2131165201;
			
			// aapt resource value: 0x7f07000d
			public const int info_welcome = 2131165197;
			
			// aapt resource value: 0x7f070007
			public const int menu_string_down = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int menu_string_left = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int menu_string_refresh = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int menu_string_right = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int menu_string_search = 2131165189;
			
			// aapt resource value: 0x7f07000b
			public const int menu_string_sort = 2131165195;
			
			// aapt resource value: 0x7f070006
			public const int menu_string_up = 2131165190;
			
			// aapt resource value: 0x7f070014
			public const int position_prompt = 2131165204;
			
			// aapt resource value: 0x7f070004
			public const int some_title = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int version = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f08002c
			public const int MyTheme = 2131230764;
			
			// aapt resource value: 0x7f08002b
			public const int TabTextAppTheme = 2131230763;
			
			// aapt resource value: 0x7f08002a
			public const int TabWidgetAppTheme = 2131230762;
			
			// aapt resource value: 0x7f080006
			public const int Theme_Splash = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int actionbar = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int actionbarhomeitem = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int actionbarhomelogo = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int actionbaritem = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int actionbarprogressbar = 2131230725;
			
			// aapt resource value: 0x7f080026
			public const int buyNowButton = 2131230758;
			
			// aapt resource value: 0x7f080002
			public const int clearbutton = 2131230722;
			
			// aapt resource value: 0x7f08000c
			public const int contentBoxHead = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int contentBoxText = 2131230733;
			
			// aapt resource value: 0x7f080015
			public const int gamesRow = 2131230741;
			
			// aapt resource value: 0x7f080025
			public const int infoSection = 2131230757;
			
			// aapt resource value: 0x7f080011
			public const int leagueInfoTableHead = 2131230737;
			
			// aapt resource value: 0x7f080009
			public const int mainButtons = 2131230729;
			
			// aapt resource value: 0x7f080010
			public const int profileInfoTableContent = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int profileInfoTableHead = 2131230735;
			
			// aapt resource value: 0x7f08000a
			public const int profileName = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int profileTableStat = 2131230731;
			
			// aapt resource value: 0x7f08001e
			public const int publicEventProfileeventAddress = 2131230750;
			
			// aapt resource value: 0x7f08001f
			public const int publicEventProfileeventDateTime = 2131230751;
			
			// aapt resource value: 0x7f080021
			public const int publicEventProfileeventDescription = 2131230753;
			
			// aapt resource value: 0x7f08001d
			public const int publicEventProfileeventLocation = 2131230749;
			
			// aapt resource value: 0x7f08001c
			public const int publicEventProfileeventName = 2131230748;
			
			// aapt resource value: 0x7f080020
			public const int publicEventProfileeventOrganizerInfo = 2131230752;
			
			// aapt resource value: 0x7f08001b
			public const int publicEventRow = 2131230747;
			
			// aapt resource value: 0x7f080019
			public const int publicEventRowStyle = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int publicEventRowTitleStyle = 2131230746;
			
			// aapt resource value: 0x7f080017
			public const int publicGameRow = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int publicGameRowHeader = 2131230742;
			
			// aapt resource value: 0x7f080018
			public const int publicGameRowTeamName = 2131230744;
			
			// aapt resource value: 0x7f080029
			public const int publicGameRowTeamScore = 2131230761;
			
			// aapt resource value: 0x7f080012
			public const int publicLeagueEventRowStyle = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int publicLeagueEventRowStyleName = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int publicLeagueMemberRowStyle = 2131230740;
			
			// aapt resource value: 0x7f080024
			public const int publicShopRowPriceStyle = 2131230756;
			
			// aapt resource value: 0x7f080023
			public const int publicShopRowStyle = 2131230755;
			
			// aapt resource value: 0x7f080022
			public const int publicShopRowTitleStyle = 2131230754;
			
			// aapt resource value: 0x7f080027
			public const int publicSkaterRowName = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int publicSkaterRowOther = 2131230760;
			
			// aapt resource value: 0x7f080008
			public const int spinnerDropDownItemStyle = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int spinnerItemStyle = 2131230727;
			
			// aapt resource value: 0x7f08000e
			public const int teamNameBtn = 2131230734;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SlidingMenu = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 3
			public const int SlidingMenu_behindOffset = 3;
			
			// aapt resource value: 5
			public const int SlidingMenu_behindScrollScale = 5;
			
			// aapt resource value: 4
			public const int SlidingMenu_behindWidth = 4;
			
			// aapt resource value: 11
			public const int SlidingMenu_fadeDegree = 11;
			
			// aapt resource value: 10
			public const int SlidingMenu_fadeEnabled = 10;
			
			// aapt resource value: 0
			public const int SlidingMenu_mode = 0;
			
			// aapt resource value: 13
			public const int SlidingMenu_selectorDrawable = 13;
			
			// aapt resource value: 12
			public const int SlidingMenu_selectorEnabled = 12;
			
			// aapt resource value: 8
			public const int SlidingMenu_shadowDrawable = 8;
			
			// aapt resource value: 9
			public const int SlidingMenu_shadowWidth = 9;
			
			// aapt resource value: 6
			public const int SlidingMenu_touchModeAbove = 6;
			
			// aapt resource value: 7
			public const int SlidingMenu_touchModeBehind = 7;
			
			// aapt resource value: 1
			public const int SlidingMenu_viewAbove = 1;
			
			// aapt resource value: 2
			public const int SlidingMenu_viewBehind = 2;
			
			public static int[] actionbar = new int[] {
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989};
			
			// aapt resource value: 3
			public const int actionbar_background = 3;
			
			// aapt resource value: 4
			public const int actionbar_background_item = 4;
			
			// aapt resource value: 6
			public const int actionbar_is_bottom = 6;
			
			// aapt resource value: 7
			public const int actionbar_light_icons = 7;
			
			// aapt resource value: 2
			public const int actionbar_separator = 2;
			
			// aapt resource value: 5
			public const int actionbar_theme = 5;
			
			// aapt resource value: 0
			public const int actionbar_title = 0;
			
			// aapt resource value: 1
			public const int actionbar_title_color = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
