using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using RDN.Library.DataModels.Base;
using System.ComponentModel.DataAnnotations.Schema;

namespace RDN.Library.DataModels.Game
{
    [Table("RDN_Game_Timeout")]
    public class GameTimeout : InheritDb
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long GameTimeOutId { get; set; }
        [Required]
        public long TimeOutTime { get; set; }
        /// <summary>
        /// generated by the client.  need this to verify what is being shown on the DB side of the house.
        /// </summary>
        [Required]
        public Guid TimeOutId { get; set; }

        #region References

        
        public virtual GameTeam GameTeam { get; set; }
        [Required]
        public virtual Game Game { get; set; }
        #endregion

    }
}
