<?xml version="1.0" encoding="utf-8"?><Database Name="Sports" Class="YafDataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=173.237.177.36;Initial Catalog=Sports;Persist Security Info=True;User ID=sportsadmin" SettingsObjectName="RDN.Library.Properties.Settings" SettingsPropertyName="SportsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.yaf_User" Member="yaf_Users">
    <Type Name="yaf_User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BoardID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProviderUserKey" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Joined" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastVisit" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IP" Type="System.String" DbType="VarChar(39)" CanBeNull="true" />
      <Column Name="NumPosts" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeZone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Signature" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AvatarImage" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AvatarImageType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RankID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Suspended" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LanguageFile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThemeFile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UseSingleSignOn" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TextEditor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OverrideDefaultThemes" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PMNotification" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AutoWatchTopics" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DailyDigest" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NotificationType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Flags" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Points" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsGuest" Type="System.Boolean" DbType="Bit" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsCaptchaExcluded" Type="System.Boolean" DbType="Bit" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsActiveExcluded" Type="System.Boolean" DbType="Bit" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsDST" Type="System.Boolean" DbType="Bit" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsDirty" Type="System.Boolean" DbType="Bit" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Culture" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="IsFacebookUser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsTwitterUser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UserStyle" Type="System.String" DbType="VarChar(510)" CanBeNull="true" />
      <Column Name="StyleFlags" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsUserStyle" Type="System.Boolean" DbType="Bit" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsGroupStyle" Type="System.Boolean" DbType="Bit" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsRankStyle" Type="System.Boolean" DbType="Bit" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>